### ISSUE TITLE
在跑lottery的時候都會斷掉

### ISSUE THREAD

**Issue by kevin930321** [chikenscrach/myba#2]
/usr/local/lib/node_modules/bahamut-automation/node_modules/playwright-core/lib/utils/debug.js:29
  if (!value) throw new Error(message || 'Assertion error');
                    ^

Error: Assertion error
    at assert (/usr/local/lib/node_modules/bahamut-automation/node_modules/playwright-core/lib/utils/debug.js:29:21)
    at FrameManager.frameAttached (/usr/local/lib/node_modules/bahamut-automation/node_modules/playwright-core/lib/server/frames.js:104:25)
    at FFPage._onFrameAttached (/usr/local/lib/node_modules/bahamut-automation/node_modules/playwright-core/lib/server/firefox/ffPage.js:171:30)
    at FFSession.emit (node:events:515:28)
    at /usr/local/lib/node_modules/bahamut-automation/node_modules/playwright-core/lib/server/firefox/ffConnection.js:160:41

Node.js v21.1.0

**Comment by chikenscrach** [comment]
這個就算是直接跑也是會出現，不是屬於ipynb上的問題，如果遇到這個問題只能多執行幾次
